module.exports = {
  500: require('./500'),
  app: require('./app'),
  bodyParser: require('./bodyParser'),
  close: require('./close'),
  compress: require('./compress'),
  cookieParser: require('./cookieParser'),
  cookieSession: require('./cookieSession'),
  cors: require('./cors'),
  csrf: require('./csrf'),
  delete: require('./delete'),
  directory: require('./directory'),
  error: require('./error'),
  get: require('./get'),
  head: require('./head'),
  json: require('./json'),
  listen: require('./listen'),
  logger: require('./logger'),
  methodOverride: require('./methodOverride'),
  multipart: require('./multipart'),
  options: require('./options'),
  patch: require('./patch'),
  post: require('./post'),
  put: require('./put'),
  route: require('./route'),
  send: require('./send'),
  urlencoded: require('./urlencoded')
}